imports:
- path: mediakind_core_vm.jinja
imports:
- path: percona-cluster_schema.jinja
imports:
- path: mediakind_role.jinja
imports:
- path: mediakind_app_role.jinja
imports:
- path: service_account.jinja
imports:
- path: core_vm_firewall_rule.jinja
imports:
- path: percona_cluster_firewall_rule.jinja
imports:
- path: db_instance_group.jinja
imports:
- path: core_instance_group.jinja
imports:
- path: core_vm_disk.jinja
imports:
- path: percona_cluster_disk.jinja
imports:
- path: firewall_rule.jinja
imports:
- path: network_core_vm_template.jinja
imports:
- path: network_percona_cluster.jinja
imports:
- path: subnet_core_vm_template.jinja
imports:
- path: subnet_percona_vm.jinja

resources:
# Create the auto-mode network
- name: mediakind-networks
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: true
    
 # Create the mediakind-core-instance-template instance
- name: mk_lam_template
  type: mediakind_core_vm.jinja
  properties:
    zone: europe-west1-b
    machineType: n1-standard-2
    containerFamily:centos-cloud
    containerImage:centos7
    network: $(ref.mediakind-network.selfLink)
    subnetwork: $(ref.mediakind-subnet.selfLink)  

# Create the percona-cluster-db-moogsoft instance
- name: percona_cluster_template
  type: percona_cluster_schema.jinja
  properties:
    zone: europe-west1-b
    machineType: n1-highmemory-2
    containerFamily:debian-cloud
    containerImage:debian7
    network: $(ref.mediakind-network.selfLink)
    subnetwork: $(ref.mediakind-subnet.selfLink)



 
