imports:
- path: mediakind_core_vm.jinja
imports:
- path: percona-cluster_schema.jinja
imports:
- path: mediakind_role.jinja
imports:
- path: mediakind_app_role.jinja
imports:
- path: service_account.jinja
imports:
- path: core_vm_firewall_rule.jinja
imports:
- path: percona_cluster_firewall_rule.jinja
imports:
- path: db_instance_group.jinja
imports:
- path: core_instance_group.jinja
imports:
- path: core_vm_disk.jinja
imports:
- path: percona_cluster_disk.jinja
imports:
- path: firewall_rule.jinja

resources:
# Create the auto-mode network
- name: mediakind-networks
  type: compute.v1.network
  properties:
    autoCreateSubnetworks: true
    
 # Create the moogsoft-core-instance-template instance
- name: mediakind_core_vm_template
  type: mediakind_core_vm.jinja
  properties:
    zone: europe-west1-b
    machineType: n1-highmem-2
    network:  https://www.googleapis.com/compute/v1/mediakind/{{ env["MediakindProject"] }}/global/networks/mediakind-networks
    subnetwork: regions/properties{["zone"]}/subnetworks/mediakind-networks

# Create the percona-cluster-db-moogsoft instance
- name: percona-cluster-db
  type: percona_cluster_db_schema.jinja
  properties:
    zone: europe-west1-b
    machineType: n1-standard-1
    network:  https://www.googleapis.com/compute/v1/mediakind/{{ env["MediakindProject"] }}/global/networks/mediakind-networks  
    subnetwork: regions/properties{["zone"]}/subnetworks/mediakind-networks



 
